// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"time"
)

type Session struct {
	ID                    string
	UserID                string
	RefreshTokenHash      []byte
	UserAgent             sql.NullString
	IpAddress             sql.NullString
	IssuedAt              time.Time
	ExpiresAt             time.Time
	RefreshTokenExpiresAt time.Time
	LastSeenAt            time.Time
	RevokedAt             sql.NullTime
}
