// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (
    id, user_id, refresh_token_hash,
    user_agent, ip_address,
    issued_at, expires_at, refresh_token_expires_at,
    last_seen_at, revoked_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID                    string
	UserID                string
	RefreshTokenHash      []byte
	UserAgent             sql.NullString
	IpAddress             sql.NullString
	IssuedAt              time.Time
	ExpiresAt             time.Time
	RefreshTokenExpiresAt time.Time
	LastSeenAt            time.Time
	RevokedAt             sql.NullTime
}

// Sessions directory
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.RefreshTokenExpiresAt,
		arg.LastSeenAt,
		arg.RevokedAt,
	)
	return err
}

const getSessionById = `-- name: GetSessionById :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, issued_at, expires_at, refresh_token_expires_at, last_seen_at, revoked_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSessionById(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, issued_at, expires_at, refresh_token_expires_at, last_seen_at, revoked_at FROM sessions WHERE refresh_token_hash = ?
`

func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshTokenHash []byte) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByRefreshHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, issued_at, expires_at, refresh_token_expires_at, last_seen_at, revoked_at FROM sessions
WHERE user_id = ?
ORDER BY issued_at DESC, id DESC
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.UserAgent,
			&i.IpAddress,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RefreshTokenExpiresAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllSessionsForUser = `-- name: RevokeAllSessionsForUser :execresult
UPDATE sessions SET revoked_at = ?
WHERE user_id = ? AND revoked_at IS NULL
`

type RevokeAllSessionsForUserParams struct {
	RevokedAt sql.NullTime
	UserID    string
}

func (q *Queries) RevokeAllSessionsForUser(ctx context.Context, arg RevokeAllSessionsForUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, revokeAllSessionsForUser, arg.RevokedAt, arg.UserID)
}

const rotateSessionRefresh = `-- name: RotateSessionRefresh :execresult
UPDATE sessions SET
    refresh_token_hash = ?, refresh_token_expires_at = ?, last_seen_at = ?
WHERE id = ? AND refresh_token_hash = ?
`

type RotateSessionRefreshParams struct {
	RefreshTokenHash      []byte
	RefreshTokenExpiresAt time.Time
	LastSeenAt            time.Time
	ID                    string
	RefreshTokenHash_2    []byte
}

func (q *Queries) RotateSessionRefresh(ctx context.Context, arg RotateSessionRefreshParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, rotateSessionRefresh,
		arg.RefreshTokenHash,
		arg.RefreshTokenExpiresAt,
		arg.LastSeenAt,
		arg.ID,
		arg.RefreshTokenHash_2,
	)
}

const updateSession = `-- name: UpdateSession :execresult
UPDATE sessions SET
    user_id = ?, refresh_token_hash = ?,
    user_agent = ?, ip_address = ?,
    issued_at = ?, expires_at = ?, refresh_token_expires_at = ?,
    last_seen_at = ?, revoked_at = ?
WHERE id = ?
`

type UpdateSessionParams struct {
	UserID                string
	RefreshTokenHash      []byte
	UserAgent             sql.NullString
	IpAddress             sql.NullString
	IssuedAt              time.Time
	ExpiresAt             time.Time
	RefreshTokenExpiresAt time.Time
	LastSeenAt            time.Time
	RevokedAt             sql.NullTime
	ID                    string
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.RefreshTokenExpiresAt,
		arg.LastSeenAt,
		arg.RevokedAt,
		arg.ID,
	)
}
