version: "3"

tasks:
    migrate:
        aliases:
            - m
        desc: "Run migrations up"
        cmds:
            - CGO_ENABLED=1 go run ./cmd/migrator/ --storage-path=./storage/sso.db --migrations-path=./migrations

    migrate-down:
        aliases:
            - md
        desc: "Rollback migrations"
        cmds:
            - CGO_ENABLED=1 go run ./cmd/migrator/ --storage-path=./storage/sso.db --migrations-path=./migrations --down
    migrate-refresh:
        aliases:
            - mr
        desc: "Refresh migrations"
        cmds:
            - task: migrate-down
            - task: migrate
    migrate_test:
        aliases:
            - mt
        desc: "Run test migrations"
        cmds:
            - CGO_ENABLED=1 go run ./cmd/migrator/ --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test
