// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_events.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createAuditEvent = `-- name: CreateAuditEvent :exec

INSERT INTO audit_events (
    id, occurred_at, event_type,
    actor_type, actor_id, actor_ip, user_agent,
    subject_type, subject_id, app_id,
    outcome, reason, metadata
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAuditEventParams struct {
	ID          string
	OccurredAt  time.Time
	EventType   string
	ActorType   uint8
	ActorID     sql.NullString
	ActorIp     sql.NullString
	UserAgent   sql.NullString
	SubjectType uint8
	SubjectID   sql.NullString
	AppID       sql.NullString
	Outcome     uint8
	Reason      sql.NullString
	Metadata    json.RawMessage
}

// Audit events queries.
//
// The aggregate is append-only — no UPDATE / DELETE here. List is
// hand-written (variable WHERE + keyset) in internal/persistence/mariadb/audit/list.go.
func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, createAuditEvent,
		arg.ID,
		arg.OccurredAt,
		arg.EventType,
		arg.ActorType,
		arg.ActorID,
		arg.ActorIp,
		arg.UserAgent,
		arg.SubjectType,
		arg.SubjectID,
		arg.AppID,
		arg.Outcome,
		arg.Reason,
		arg.Metadata,
	)
	return err
}

const getAuditEventByID = `-- name: GetAuditEventByID :one
SELECT id, occurred_at, event_type, actor_type, actor_id, actor_ip, user_agent, subject_type, subject_id, app_id, outcome, reason, metadata FROM audit_events WHERE id = ?
`

func (q *Queries) GetAuditEventByID(ctx context.Context, id string) (AuditEvent, error) {
	row := q.db.QueryRowContext(ctx, getAuditEventByID, id)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.EventType,
		&i.ActorType,
		&i.ActorID,
		&i.ActorIp,
		&i.UserAgent,
		&i.SubjectType,
		&i.SubjectID,
		&i.AppID,
		&i.Outcome,
		&i.Reason,
		&i.Metadata,
	)
	return i, err
}
