// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AuditEvent struct {
	ID          string
	OccurredAt  time.Time
	EventType   string
	ActorType   uint8
	ActorID     sql.NullString
	ActorIp     sql.NullString
	UserAgent   sql.NullString
	SubjectType uint8
	SubjectID   sql.NullString
	AppID       sql.NullString
	Outcome     uint8
	Reason      sql.NullString
	Metadata    json.RawMessage
}
