// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"time"
)

type ServiceAccount struct {
	ID                  string
	Name                string
	Description         string
	ClientSecretHash    []byte
	Status              uint8
	Etag                string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	LastAuthenticatedAt sql.NullTime
}
