// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: serviceAccounts.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const countServiceAccountByID = `-- name: CountServiceAccountByID :one
SELECT COUNT(*) FROM service_accounts WHERE id = ?
`

// Used by the repository to discriminate ErrServiceAccountNotFound vs
// ErrEtagMismatch after a 0-rows-affected UPDATE/DELETE.
func (q *Queries) CountServiceAccountByID(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countServiceAccountByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createServiceAccount = `-- name: CreateServiceAccount :exec
INSERT INTO service_accounts
    (id, name, description, client_secret_hash, status, etag, created_at, updated_at, last_authenticated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateServiceAccountParams struct {
	ID                  string
	Name                string
	Description         string
	ClientSecretHash    []byte
	Status              uint8
	Etag                string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	LastAuthenticatedAt sql.NullTime
}

func (q *Queries) CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) error {
	_, err := q.db.ExecContext(ctx, createServiceAccount,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ClientSecretHash,
		arg.Status,
		arg.Etag,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastAuthenticatedAt,
	)
	return err
}

const deleteServiceAccount = `-- name: DeleteServiceAccount :execresult
DELETE FROM service_accounts WHERE id = ?
`

func (q *Queries) DeleteServiceAccount(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteServiceAccount, id)
}

const deleteServiceAccountWithEtag = `-- name: DeleteServiceAccountWithEtag :execresult
DELETE FROM service_accounts WHERE id = ? AND etag = ?
`

type DeleteServiceAccountWithEtagParams struct {
	ID   string
	Etag string
}

func (q *Queries) DeleteServiceAccountWithEtag(ctx context.Context, arg DeleteServiceAccountWithEtagParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteServiceAccountWithEtag, arg.ID, arg.Etag)
}

const getServiceAccountById = `-- name: GetServiceAccountById :one
SELECT id, name, description, client_secret_hash, status, etag,
    created_at, updated_at, last_authenticated_at
FROM service_accounts
WHERE id = ?
`

func (q *Queries) GetServiceAccountById(ctx context.Context, id string) (ServiceAccount, error) {
	row := q.db.QueryRowContext(ctx, getServiceAccountById, id)
	var i ServiceAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ClientSecretHash,
		&i.Status,
		&i.Etag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastAuthenticatedAt,
	)
	return i, err
}

const updateServiceAccount = `-- name: UpdateServiceAccount :execresult
UPDATE service_accounts SET
    name = ?, description = ?, client_secret_hash = ?, status = ?, etag = ?,
    updated_at = ?, last_authenticated_at = ?
WHERE id = ?
`

type UpdateServiceAccountParams struct {
	Name                string
	Description         string
	ClientSecretHash    []byte
	Status              uint8
	Etag                string
	UpdatedAt           time.Time
	LastAuthenticatedAt sql.NullTime
	ID                  string
}

func (q *Queries) UpdateServiceAccount(ctx context.Context, arg UpdateServiceAccountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateServiceAccount,
		arg.Name,
		arg.Description,
		arg.ClientSecretHash,
		arg.Status,
		arg.Etag,
		arg.UpdatedAt,
		arg.LastAuthenticatedAt,
		arg.ID,
	)
}

const updateServiceAccountWithEtag = `-- name: UpdateServiceAccountWithEtag :execresult
UPDATE service_accounts SET
    name = ?, description = ?, client_secret_hash = ?, status = ?, etag = ?,
    updated_at = ?, last_authenticated_at = ?
WHERE id = ? AND etag = ?
`

type UpdateServiceAccountWithEtagParams struct {
	Name                string
	Description         string
	ClientSecretHash    []byte
	Status              uint8
	Etag                string
	UpdatedAt           time.Time
	LastAuthenticatedAt sql.NullTime
	ID                  string
	Etag_2              string
}

// Single write-path covers admin updates (name/description/status) AND
// credential rotation (client_secret_hash). The aggregate carries the
// canonical post-mutation state; the row is rewritten in full.
func (q *Queries) UpdateServiceAccountWithEtag(ctx context.Context, arg UpdateServiceAccountWithEtagParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateServiceAccountWithEtag,
		arg.Name,
		arg.Description,
		arg.ClientSecretHash,
		arg.Status,
		arg.Etag,
		arg.UpdatedAt,
		arg.LastAuthenticatedAt,
		arg.ID,
		arg.Etag_2,
	)
}
