// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"time"
)

type RecoveryCode struct {
	BatchID  string
	CodeHash []byte
	UsedAt   sql.NullTime
}

type RecoveryCodeBatch struct {
	ID          string
	UserID      string
	GeneratedAt time.Time
	RevokedAt   sql.NullTime
}
