// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recovery_codes.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :execresult
UPDATE recovery_codes
SET used_at = ?
WHERE batch_id = ? AND code_hash = ? AND used_at IS NULL
`

type ConsumeRecoveryCodeParams struct {
	UsedAt   sql.NullTime
	BatchID  string
	CodeHash []byte
}

func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, consumeRecoveryCode, arg.UsedAt, arg.BatchID, arg.CodeHash)
}

const createRecoveryCode = `-- name: CreateRecoveryCode :exec
INSERT INTO recovery_codes (
    batch_id, code_hash, used_at
) VALUES (?, ?, ?)
`

type CreateRecoveryCodeParams struct {
	BatchID  string
	CodeHash []byte
	UsedAt   sql.NullTime
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error {
	_, err := q.db.ExecContext(ctx, createRecoveryCode, arg.BatchID, arg.CodeHash, arg.UsedAt)
	return err
}

const createRecoveryCodeBatch = `-- name: CreateRecoveryCodeBatch :exec

INSERT INTO recovery_code_batches (
    id, user_id, generated_at, revoked_at
) VALUES (?, ?, ?, ?)
`

type CreateRecoveryCodeBatchParams struct {
	ID          string
	UserID      string
	GeneratedAt time.Time
	RevokedAt   sql.NullTime
}

// Recovery-code batches and their codes.
func (q *Queries) CreateRecoveryCodeBatch(ctx context.Context, arg CreateRecoveryCodeBatchParams) error {
	_, err := q.db.ExecContext(ctx, createRecoveryCodeBatch,
		arg.ID,
		arg.UserID,
		arg.GeneratedAt,
		arg.RevokedAt,
	)
	return err
}

const getActiveRecoveryBatchByUser = `-- name: GetActiveRecoveryBatchByUser :one
SELECT id, user_id, generated_at, revoked_at FROM recovery_code_batches
WHERE user_id = ? AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveRecoveryBatchByUser(ctx context.Context, userID string) (RecoveryCodeBatch, error) {
	row := q.db.QueryRowContext(ctx, getActiveRecoveryBatchByUser, userID)
	var i RecoveryCodeBatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GeneratedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listRecoveryCodesByBatch = `-- name: ListRecoveryCodesByBatch :many
SELECT batch_id, code_hash, used_at FROM recovery_codes
WHERE batch_id = ?
`

func (q *Queries) ListRecoveryCodesByBatch(ctx context.Context, batchID string) ([]RecoveryCode, error) {
	rows, err := q.db.QueryContext(ctx, listRecoveryCodesByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoveryCode{}
	for rows.Next() {
		var i RecoveryCode
		if err := rows.Scan(&i.BatchID, &i.CodeHash, &i.UsedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeActiveRecoveryBatchesForUser = `-- name: RevokeActiveRecoveryBatchesForUser :execresult
UPDATE recovery_code_batches
SET revoked_at = ?
WHERE user_id = ? AND revoked_at IS NULL
`

type RevokeActiveRecoveryBatchesForUserParams struct {
	RevokedAt sql.NullTime
	UserID    string
}

func (q *Queries) RevokeActiveRecoveryBatchesForUser(ctx context.Context, arg RevokeActiveRecoveryBatchesForUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, revokeActiveRecoveryBatchesForUser, arg.RevokedAt, arg.UserID)
}

const revokeRecoveryBatch = `-- name: RevokeRecoveryBatch :execresult
UPDATE recovery_code_batches
SET revoked_at = ?
WHERE id = ? AND revoked_at IS NULL
`

type RevokeRecoveryBatchParams struct {
	RevokedAt sql.NullTime
	ID        string
}

func (q *Queries) RevokeRecoveryBatch(ctx context.Context, arg RevokeRecoveryBatchParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, revokeRecoveryBatch, arg.RevokedAt, arg.ID)
}
