// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const countUserByID = `-- name: CountUserByID :one
SELECT COUNT(*) FROM users WHERE id = ?
`

// Used by the repository to discriminate ErrUserNotFound vs
// ErrEtagMismatch after a 0-rows-affected UPDATE/DELETE.
func (q *Queries) CountUserByID(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec

INSERT INTO users
    (id, email, username, password_hash, display_name, avatar_url, locale, timezone,
     status, etag, created_at, updated_at, last_login_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           string
	Email        string
	Username     string
	PasswordHash sql.NullString
	DisplayName  string
	AvatarUrl    sql.NullString
	Locale       string
	Timezone     string
	Status       uint8
	Etag         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LastLoginAt  sql.NullTime
}

// Identity directory: per-row queries. Dynamic ListUsers lives in the
// repository's hand-written list.go (sqlc cannot template variable WHERE /
// ORDER BY economically).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Locale,
		arg.Timezone,
		arg.Status,
		arg.Etag,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastLoginAt,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :execresult
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUser, id)
}

const deleteUserWithEtag = `-- name: DeleteUserWithEtag :execresult
DELETE FROM users WHERE id = ? AND etag = ?
`

type DeleteUserWithEtagParams struct {
	ID   string
	Etag string
}

func (q *Queries) DeleteUserWithEtag(ctx context.Context, arg DeleteUserWithEtagParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUserWithEtag, arg.ID, arg.Etag)
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, display_name, avatar_url, locale, timezone, status, etag, created_at, updated_at, last_login_at, failed_login_attempts, lockout_until FROM users
WHERE email = ?
`

// Used by AuthService.Login when the caller authenticates by email.
// Returns the full row including password_hash so the use-case can run
// bcrypt verification without a follow-up Get.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.Status,
		&i.Etag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.FailedLoginAttempts,
		&i.LockoutUntil,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, password_hash, display_name, avatar_url, locale, timezone, status, etag, created_at, updated_at, last_login_at, failed_login_attempts, lockout_until FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.Status,
		&i.Etag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.FailedLoginAttempts,
		&i.LockoutUntil,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password_hash, display_name, avatar_url, locale, timezone, status, etag, created_at, updated_at, last_login_at, failed_login_attempts, lockout_until FROM users
WHERE username = ?
`

// Used by AuthService.Login when the caller authenticates by username.
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.Status,
		&i.Etag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.FailedLoginAttempts,
		&i.LockoutUntil,
	)
	return i, err
}

const incrementFailedLogins = `-- name: IncrementFailedLogins :execresult
UPDATE users SET
    failed_login_attempts = failed_login_attempts + 1
WHERE id = ?
`

func (q *Queries) IncrementFailedLogins(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, incrementFailedLogins, id)
}

const lockUser = `-- name: LockUser :execresult
UPDATE users SET
    lockout_until = ?, failed_login_attempts = 0
WHERE id = ?
`

type LockUserParams struct {
	LockoutUntil sql.NullTime
	ID           string
}

func (q *Queries) LockUser(ctx context.Context, arg LockUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, lockUser, arg.LockoutUntil, arg.ID)
}

const resetLoginFailures = `-- name: ResetLoginFailures :execresult
UPDATE users SET
    failed_login_attempts = 0, lockout_until = NULL
WHERE id = ?
`

func (q *Queries) ResetLoginFailures(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, resetLoginFailures, id)
}

const updateUser = `-- name: UpdateUser :execresult
UPDATE users SET
    email = ?, username = ?, display_name = ?, password_hash = ?, avatar_url = ?,
    locale = ?, timezone = ?, status = ?, etag = ?,
    updated_at = ?, last_login_at = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Email        string
	Username     string
	DisplayName  string
	PasswordHash sql.NullString
	AvatarUrl    sql.NullString
	Locale       string
	Timezone     string
	Status       uint8
	Etag         string
	UpdatedAt    time.Time
	LastLoginAt  sql.NullTime
	ID           string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.AvatarUrl,
		arg.Locale,
		arg.Timezone,
		arg.Status,
		arg.Etag,
		arg.UpdatedAt,
		arg.LastLoginAt,
		arg.ID,
	)
}

const updateUserLastLoginAt = `-- name: UpdateUserLastLoginAt :execresult
UPDATE users SET
    last_login_at = ?
WHERE id = ?
`

type UpdateUserLastLoginAtParams struct {
	LastLoginAt sql.NullTime
	ID          string
}

func (q *Queries) UpdateUserLastLoginAt(ctx context.Context, arg UpdateUserLastLoginAtParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserLastLoginAt, arg.LastLoginAt, arg.ID)
}

const updateUserPasswordWithEtag = `-- name: UpdateUserPasswordWithEtag :execresult
UPDATE users SET
    password_hash = ?, etag = ?, updated_at = ?
WHERE id = ? AND etag = ?
`

type UpdateUserPasswordWithEtagParams struct {
	PasswordHash sql.NullString
	Etag         string
	UpdatedAt    time.Time
	ID           string
	Etag_2       string
}

func (q *Queries) UpdateUserPasswordWithEtag(ctx context.Context, arg UpdateUserPasswordWithEtagParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserPasswordWithEtag,
		arg.PasswordHash,
		arg.Etag,
		arg.UpdatedAt,
		arg.ID,
		arg.Etag_2,
	)
}

const updateUserWithEtag = `-- name: UpdateUserWithEtag :execresult
UPDATE users SET
    email = ?, username = ?, display_name = ?, password_hash = ?, avatar_url = ?,
    locale = ?, timezone = ?, status = ?, etag = ?,
    updated_at = ?, last_login_at = ?
WHERE id = ? AND etag = ?
`

type UpdateUserWithEtagParams struct {
	Email        string
	Username     string
	DisplayName  string
	PasswordHash sql.NullString
	AvatarUrl    sql.NullString
	Locale       string
	Timezone     string
	Status       uint8
	Etag         string
	UpdatedAt    time.Time
	LastLoginAt  sql.NullTime
	ID           string
	Etag_2       string
}

func (q *Queries) UpdateUserWithEtag(ctx context.Context, arg UpdateUserWithEtagParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserWithEtag,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.AvatarUrl,
		arg.Locale,
		arg.Timezone,
		arg.Status,
		arg.Etag,
		arg.UpdatedAt,
		arg.LastLoginAt,
		arg.ID,
		arg.Etag_2,
	)
}
