// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"encoding/json"
	"time"
)

type App struct {
	ID        string
	Name      string
	Slug      string
	Link      string
	Status    uint8
	Etag      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AuditEvent struct {
	ID          string
	OccurredAt  time.Time
	EventType   string
	ActorType   uint8
	ActorID     sql.NullString
	ActorIp     sql.NullString
	UserAgent   sql.NullString
	SubjectType uint8
	SubjectID   sql.NullString
	AppID       sql.NullString
	Outcome     uint8
	Reason      sql.NullString
	Metadata    json.RawMessage
}

type RecoveryCode struct {
	BatchID  string
	CodeHash []byte
	UsedAt   sql.NullTime
}

type RecoveryCodeBatch struct {
	ID          string
	UserID      string
	GeneratedAt time.Time
	RevokedAt   sql.NullTime
}

type Role struct {
	ID          string
	AppID       string
	Name        string
	Description sql.NullString
	Status      uint8
	Etag        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RoleAssignment struct {
	UserID          string
	RoleID          string
	AppID           string
	GrantedByUserID string
	GrantedAt       time.Time
}

type RolePermission struct {
	RoleID     string
	Permission string
}

type ServiceAccount struct {
	ID                  string
	Name                string
	Description         string
	ClientSecretHash    []byte
	Status              uint8
	Etag                string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	LastAuthenticatedAt sql.NullTime
}

type Session struct {
	ID                    string
	UserID                string
	RefreshTokenHash      []byte
	UserAgent             sql.NullString
	IpAddress             sql.NullString
	IssuedAt              time.Time
	ExpiresAt             time.Time
	RefreshTokenExpiresAt time.Time
	LastSeenAt            time.Time
	RevokedAt             sql.NullTime
}

type User struct {
	ID           string
	Email        string
	Username     string
	PasswordHash sql.NullString
	DisplayName  string
	AvatarUrl    sql.NullString
	Locale       string
	Timezone     string
	Status       uint8
	Etag         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LastLoginAt  sql.NullTime
}
