// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const countRoleByID = `-- name: CountRoleByID :one
SELECT COUNT(*) FROM roles WHERE id = ?
`

// Used by the repository to discriminate ErrRoleNotFound vs
// ErrEtagMismatch after a 0-rows-affected UPDATE/DELETE.
func (q *Queries) CountRoleByID(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRoleByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :exec

INSERT INTO roles
    (id, app_id, name, description, status, etag, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRoleParams struct {
	ID          string
	AppID       string
	Name        string
	Description sql.NullString
	Status      uint8
	Etag        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Roles directory: per-row queries plus permission-management helpers.
// Dynamic ListRoles lives in the repository's hand-written list.go (sqlc
// cannot template variable WHERE / ORDER BY economically).
//
// Permissions live in a separate role_permissions table (one row per
// (role_id, permission)). The role aggregate and its permission set are
// two distinct write surfaces here; the repository wraps them in a single
// transaction when atomicity matters — CreateRole (insert row + insert
// N permissions) and UpdateRole with mask containing "permissions" (wipe
// old set + insert new set).
//
// Lifecycle (DisableRole / EnableRole) goes through UpdateRole at the
// service layer: the domain mutator advances status + etag + updated_at,
// and the repo persists with UpdateRole (unconditional path), keeping the
// optimistic-locking invariant intact. There are intentionally no
// dedicated Disable/Enable SQL statements — they would silently bypass
// the etag bump and leave clients with a stale concurrency token.
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.ExecContext(ctx, createRole,
		arg.ID,
		arg.AppID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Etag,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteRole = `-- name: DeleteRole :execresult
DELETE FROM roles WHERE id = ?
`

func (q *Queries) DeleteRole(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteRole, id)
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = ?
`

// Wipes all permissions for a role. Used by UpdateRole.permissions: the
// repository wipes then re-inserts the new set inside a single tx.
func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID string) error {
	_, err := q.db.ExecContext(ctx, deleteRolePermissions, roleID)
	return err
}

const deleteRoleWithEtag = `-- name: DeleteRoleWithEtag :execresult
DELETE FROM roles WHERE id = ? AND etag = ?
`

type DeleteRoleWithEtagParams struct {
	ID   string
	Etag string
}

func (q *Queries) DeleteRoleWithEtag(ctx context.Context, arg DeleteRoleWithEtagParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteRoleWithEtag, arg.ID, arg.Etag)
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, app_id, name, description, status, etag, created_at, updated_at
FROM roles
WHERE id = ?
`

func (q *Queries) GetRoleByID(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Etag,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRolePermissions = `-- name: GetRolePermissions :many

SELECT permission FROM role_permissions WHERE role_id = ? ORDER BY permission
`

// ============================================================================
// Permissions (role_permissions join table)
// ============================================================================
// Returns a role's permissions in a deterministic order so callers can
// build a stable string slice without an extra in-memory sort.
func (q *Queries) GetRolePermissions(ctx context.Context, roleID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRolePermission = `-- name: InsertRolePermission :exec
INSERT INTO role_permissions (role_id, permission) VALUES (?, ?)
`

type InsertRolePermissionParams struct {
	RoleID     string
	Permission string
}

// Inserts a single (role_id, permission) row. Callers (CreateRole and
// UpdateRole with mask containing "permissions") loop over the role's
// permission slice inside a transaction.
func (q *Queries) InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) error {
	_, err := q.db.ExecContext(ctx, insertRolePermission, arg.RoleID, arg.Permission)
	return err
}

const updateRole = `-- name: UpdateRole :execresult
UPDATE roles SET
    name = ?, description = ?, status = ?, etag = ?, updated_at = ?
WHERE id = ?
`

type UpdateRoleParams struct {
	Name        string
	Description sql.NullString
	Status      uint8
	Etag        string
	UpdatedAt   time.Time
	ID          string
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateRole,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Etag,
		arg.UpdatedAt,
		arg.ID,
	)
}

const updateRoleWithEtag = `-- name: UpdateRoleWithEtag :execresult
UPDATE roles SET
    name = ?, description = ?, status = ?, etag = ?, updated_at = ?
WHERE id = ? AND etag = ?
`

type UpdateRoleWithEtagParams struct {
	Name        string
	Description sql.NullString
	Status      uint8
	Etag        string
	UpdatedAt   time.Time
	ID          string
	Etag_2      string
}

func (q *Queries) UpdateRoleWithEtag(ctx context.Context, arg UpdateRoleWithEtagParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateRoleWithEtag,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Etag,
		arg.UpdatedAt,
		arg.ID,
		arg.Etag_2,
	)
}
