// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roleAssignments.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const countRoleAssignmentsByUserApp = `-- name: CountRoleAssignmentsByUserApp :one
SELECT COUNT(*) FROM role_assignments WHERE user_id = ? AND app_id = ?
`

type CountRoleAssignmentsByUserAppParams struct {
	UserID string
	AppID  string
}

func (q *Queries) CountRoleAssignmentsByUserApp(ctx context.Context, arg CountRoleAssignmentsByUserAppParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRoleAssignmentsByUserApp, arg.UserID, arg.AppID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoleAssignment = `-- name: CreateRoleAssignment :exec
INSERT INTO role_assignments
    (user_id, role_id, app_id, granted_by_user_id, granted_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateRoleAssignmentParams struct {
	UserID          string
	RoleID          string
	AppID           string
	GrantedByUserID string
	GrantedAt       time.Time
}

// Idempotent insert: callers wrap with INSERT IGNORE-style discrimination
// via dbutil.IsDuplicateEntry — the use-case wants "already existed" to
// be observable so it can populate `newly_created=false` in BulkGrantRoles.
func (q *Queries) CreateRoleAssignment(ctx context.Context, arg CreateRoleAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, createRoleAssignment,
		arg.UserID,
		arg.RoleID,
		arg.AppID,
		arg.GrantedByUserID,
		arg.GrantedAt,
	)
	return err
}

const deleteRoleAssignment = `-- name: DeleteRoleAssignment :execresult
DELETE FROM role_assignments WHERE user_id = ? AND role_id = ?
`

type DeleteRoleAssignmentParams struct {
	UserID string
	RoleID string
}

func (q *Queries) DeleteRoleAssignment(ctx context.Context, arg DeleteRoleAssignmentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteRoleAssignment, arg.UserID, arg.RoleID)
}

const getRoleAssignment = `-- name: GetRoleAssignment :one
SELECT user_id, role_id, app_id, granted_by_user_id, granted_at
FROM role_assignments
WHERE user_id = ? AND role_id = ?
`

type GetRoleAssignmentParams struct {
	UserID string
	RoleID string
}

func (q *Queries) GetRoleAssignment(ctx context.Context, arg GetRoleAssignmentParams) (RoleAssignment, error) {
	row := q.db.QueryRowContext(ctx, getRoleAssignment, arg.UserID, arg.RoleID)
	var i RoleAssignment
	err := row.Scan(
		&i.UserID,
		&i.RoleID,
		&i.AppID,
		&i.GrantedByUserID,
		&i.GrantedAt,
	)
	return i, err
}

const listActivePermissionsByUserApp = `-- name: ListActivePermissionsByUserApp :many
SELECT r.id AS role_id, rp.permission
FROM role_assignments ra
JOIN roles r           ON r.id = ra.role_id
JOIN role_permissions rp ON rp.role_id = r.id
WHERE ra.user_id = ?
  AND ra.app_id  = ?
  AND r.status   = ?
`

type ListActivePermissionsByUserAppParams struct {
	UserID string
	AppID  string
	Status uint8
}

type ListActivePermissionsByUserAppRow struct {
	RoleID     string
	Permission string
}

// Returns all permission strings carried by ACTIVE roles assigned to the
// user in the target app. Drives CheckPermission and BatchCheckPermission;
// DISABLED roles are filtered server-side at the JOIN. Each (role_id,
// permission) row is returned once — duplicates across roles ARE possible
// and the caller (use-case layer) does the wildcard expansion + dedup
// against the requested permission set.
func (q *Queries) ListActivePermissionsByUserApp(ctx context.Context, arg ListActivePermissionsByUserAppParams) ([]ListActivePermissionsByUserAppRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivePermissionsByUserApp, arg.UserID, arg.AppID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePermissionsByUserAppRow{}
	for rows.Next() {
		var i ListActivePermissionsByUserAppRow
		if err := rows.Scan(&i.RoleID, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
