package domain

const (
	ReasonInternal                    = "ERROR_REASON_INTERNAL"
	ReasonInvalidCredentials          = "ERROR_REASON_INVALID_CREDENTIALS"
	ReasonInvalidToken                = "ERROR_REASON_INVALID_TOKEN"
	ReasonRefreshTokenReused          = "ERROR_REASON_REFRESH_TOKEN_REUSED"
	ReasonSessionNotFound             = "ERROR_REASON_SESSION_NOT_FOUND"
	ReasonPasswordMismatch            = "ERROR_REASON_PASSWORD_MISMATCH"
	ReasonValidationFailed            = "ERROR_REASON_VALIDATION_FAILED"
	ReasonEtagMismatch                = "ERROR_REASON_ETAG_MISMATCH"
	ReasonUserAlreadyExists           = "ERROR_REASON_USER_ALREADY_EXISTS"
	ReasonUserBlocked                 = "ERROR_REASON_USER_BLOCKED"
	ReasonUserDeleted                 = "ERROR_REASON_USER_DELETED"
	ReasonUserNotFound                = "ERROR_REASON_USER_NOT_FOUND"
	ReasonUserNotDeleted              = "ERROR_REASON_USER_NOT_DELETED"
	ReasonUserNotEligible             = "ERROR_REASON_USER_NOT_ELIGIBLE"
	ReasonAppNotFound                 = "ERROR_REASON_APP_NOT_FOUND"
	ReasonAppAlreadyExists            = "ERROR_REASON_APP_ALREADY_EXISTS"
	ReasonAppDisabled                 = "ERROR_REASON_APP_DISABLED"
	ReasonAppInMaintenance            = "ERROR_REASON_APP_IN_MAINTENANCE"
	ReasonRoleNotFound                = "ERROR_REASON_ROLE_NOT_FOUND"
	ReasonRoleAlreadyExists           = "ERROR_REASON_ROLE_ALREADY_EXISTS"
	ReasonRoleDisabled                = "ERROR_REASON_ROLE_DISABLED"
	ReasonRoleNotInApp                = "ERROR_REASON_ROLE_NOT_IN_APP"
	ReasonPermissionDenied            = "ERROR_REASON_PERMISSION_DENIED"
	ReasonRecoveryCodeInvalid         = "ERROR_REASON_RECOVERY_CODE_INVALID"
	ReasonServiceAccountNotFound      = "ERROR_REASON_SERVICE_ACCOUNT_NOT_FOUND"
	ReasonServiceAccountAlreadyExists = "ERROR_REASON_SERVICE_ACCOUNT_ALREADY_EXISTS"
	ReasonServiceAccountDisabled      = "ERROR_REASON_SERVICE_ACCOUNT_DISABLED"
	ReasonInvalidClientCredentials    = "ERROR_REASON_INVALID_CLIENT_CREDENTIALS"
	ReasonRateLimited                 = "ERROR_REASON_RATE_LIMITED"
)
