// Package domain holds the Batch aggregate for the recoverycode bounded
// context (one-time codes that let a user reset their password offline,
// no SMTP, no admin).
//
// One Batch is one set of ten codes generated by GenerateRecoveryCodes;
// each Code is single-use. The aggregate stores only salted-free SHA-256
// hashes — plaintext is shown to the user exactly once and discarded.
// Codes are case-insensitive and accept the canonical "XXXX-XXXX-XXXX"
// shape with or without hyphens; normalisation lives in the platform
// generator, not the aggregate.
//
// Lifecycle:
//
//   - On Generate, the use-case revokes the previous batch (if any) and
//     creates a fresh one. The "max one active batch per user" invariant
//     is enforced by the use-case + repository; the aggregate itself does
//     not know about its siblings.
//   - On Consume, exactly one Code transitions from "unused" to "used";
//     subsequent attempts with the same hash surface ErrRecoveryCodeInvalid.
//   - Revoke is one-way and idempotent.
package domain

import (
	"bytes"
	"fmt"
	"time"

	"sso/internal/kernel/validation"

	"github.com/google/uuid"
)

// ----------------------------------------------------------------------------
// Cross-context UUID handles
// ----------------------------------------------------------------------------

// BatchID is owned by this bounded context. UserID is a cross-context
// handle to the identity.User aggregate; declared as a typed alias here
// to keep this package free of an identity import.
type BatchID string
type UserID string

func NewBatchID() (BatchID, error) {
	id, err := uuid.NewV7()
	if err != nil {
		return "", fmt.Errorf("generate batch id: %w", err)
	}
	return BatchID(id.String()), nil
}

func ParseBatchID(s string) (BatchID, error) {
	if _, err := uuid.Parse(s); err != nil {
		return "", &validation.Error{Field: "batch_id", Reason: "must be a valid UUID"}
	}
	return BatchID(s), nil
}

func (b BatchID) String() string { return string(b) }
func (u UserID) String() string  { return string(u) }

// ----------------------------------------------------------------------------
// Code — one entry in a batch
// ----------------------------------------------------------------------------

// Code is one row in recovery_codes. hash is SHA-256 of the normalised
// plaintext (uppercase, hyphens stripped); usedAt is zero while the
// code is unused, set on Consume to mark it spent. Plaintext lives only
// in the response of GenerateRecoveryCodes — the server never stores it.
type Code struct {
	hash   []byte
	usedAt time.Time // zero = unused
}

func NewCode(hash []byte) Code {
	return Code{hash: hash}
}

func RestoreCode(hash []byte, usedAt time.Time) Code {
	return Code{hash: hash, usedAt: usedAt}
}

func (c Code) Hash() []byte      { return c.hash }
func (c Code) UsedAt() time.Time { return c.usedAt }
func (c Code) IsUsed() bool      { return !c.usedAt.IsZero() }

// ----------------------------------------------------------------------------
// Batch aggregate
// ----------------------------------------------------------------------------

// Batch is one generation of recovery codes for a user.
//
// Field visibility split mirrors session/identity: id, userID, timestamps
// are unexported (immutable after construction except for revokedAt and
// per-code usedAt, both advanced only via aggregate methods). codes are
// kept private as well — callers iterate via Codes().
type Batch struct {
	id          BatchID
	userID      UserID
	generatedAt time.Time
	revokedAt   time.Time // zero = active
	codes       []Code
}

// NewBatchParams is what the use-case supplies. Codes carry only the
// hashes; plaintext is returned to the client by the use-case and is
// not part of the aggregate state.
type NewBatchParams struct {
	ID          BatchID
	UserID      UserID
	GeneratedAt time.Time
	CodeHashes  [][]byte
}

func NewBatch(p NewBatchParams) *Batch {
	codes := make([]Code, len(p.CodeHashes))
	for i, h := range p.CodeHashes {
		codes[i] = NewCode(h)
	}
	return &Batch{
		id:          p.ID,
		userID:      p.UserID,
		generatedAt: p.GeneratedAt,
		codes:       codes,
	}
}

// RestoreBatchParams is the full row read back from the repository.
// Trusted: it was written by NewBatch / Revoke / Consume earlier.
type RestoreBatchParams struct {
	ID          BatchID
	UserID      UserID
	GeneratedAt time.Time
	RevokedAt   time.Time // zero = active
	Codes       []Code
}

func RestoreBatch(p RestoreBatchParams) *Batch {
	return &Batch{
		id:          p.ID,
		userID:      p.UserID,
		generatedAt: p.GeneratedAt,
		revokedAt:   p.RevokedAt,
		codes:       p.Codes,
	}
}

// Accessors.
func (b *Batch) ID() BatchID            { return b.id }
func (b *Batch) UserID() UserID         { return b.userID }
func (b *Batch) GeneratedAt() time.Time { return b.generatedAt }
func (b *Batch) RevokedAt() time.Time   { return b.revokedAt }
func (b *Batch) Codes() []Code          { return b.codes }

func (b *Batch) IsRevoked() bool { return !b.revokedAt.IsZero() }

// ----------------------------------------------------------------------------
// Mutators
// ----------------------------------------------------------------------------

// Revoke marks the batch as revoked. Idempotent.
func (b *Batch) Revoke(now time.Time) {
	if b.IsRevoked() {
		return
	}
	b.revokedAt = now
}

// ConsumeByHash flips exactly one matching unused code to "used". Returns
// ErrRecoveryCodeInvalid when the hash is not in the batch, has already
// been used, or the batch itself is revoked. The conditional UPDATE at
// the repo layer is the authoritative single-use guard; this method
// keeps the same invariant locally so an in-memory aggregate (tests,
// future SQLite mirror) behaves the same way.
func (b *Batch) ConsumeByHash(hash []byte, now time.Time) error {
	if b.IsRevoked() {
		return ErrRecoveryCodeInvalid
	}
	for i := range b.codes {
		if !bytes.Equal(b.codes[i].hash, hash) {
			continue
		}
		if b.codes[i].IsUsed() {
			return ErrRecoveryCodeInvalid
		}
		b.codes[i].usedAt = now
		return nil
	}
	return ErrRecoveryCodeInvalid
}
