name: Release

permissions:
    contents: write

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.22"

            - name: Build binary
              run: |
                  go mod tidy
                  go build -ldflags "-X main.version=${GITHUB_REF_NAME} \
                                      -X main.commit=$(git rev-parse --short HEAD) \
                                      -X main.date=$(date +%Y-%m-%d)" \
                            -o main ./cmd/sso

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: main
