// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apps.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const countAppByID = `-- name: CountAppByID :one
SELECT COUNT(*) FROM apps WHERE id = ?
`

// Used by the repository to discriminate ErrAppNotFound vs
// ErrEtagMismatch after a 0-rows-affected UPDATE/DELETE.
func (q *Queries) CountAppByID(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApp = `-- name: CreateApp :exec

INSERT INTO apps
    (id, name, slug, link, status, etag, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAppParams struct {
	ID        string
	Name      string
	Slug      string
	Link      string
	Status    uint8
	Etag      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Apps directory: per-row queries. Dynamic ListApps lives in the
// repository's hand-written list.go.
func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) error {
	_, err := q.db.ExecContext(ctx, createApp,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Link,
		arg.Status,
		arg.Etag,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteApp = `-- name: DeleteApp :execresult
DELETE FROM apps WHERE id = ?
`

func (q *Queries) DeleteApp(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteApp, id)
}

const deleteAppWithEtag = `-- name: DeleteAppWithEtag :execresult
DELETE FROM apps WHERE id = ? AND etag = ?
`

type DeleteAppWithEtagParams struct {
	ID   string
	Etag string
}

func (q *Queries) DeleteAppWithEtag(ctx context.Context, arg DeleteAppWithEtagParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAppWithEtag, arg.ID, arg.Etag)
}

const getAppByID = `-- name: GetAppByID :one
SELECT id, name, slug, link, status, etag, created_at, updated_at
FROM apps
WHERE id = ?
`

func (q *Queries) GetAppByID(ctx context.Context, id string) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByID, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Link,
		&i.Status,
		&i.Etag,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApp = `-- name: UpdateApp :execresult
UPDATE apps SET
    name = ?, link = ?, status = ?, etag = ?, updated_at = ?
WHERE id = ?
`

type UpdateAppParams struct {
	Name      string
	Link      string
	Status    uint8
	Etag      string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateApp,
		arg.Name,
		arg.Link,
		arg.Status,
		arg.Etag,
		arg.UpdatedAt,
		arg.ID,
	)
}

const updateAppWithEtag = `-- name: UpdateAppWithEtag :execresult
UPDATE apps SET
    name = ?, link = ?, status = ?, etag = ?, updated_at = ?
WHERE id = ? AND etag = ?
`

type UpdateAppWithEtagParams struct {
	Name      string
	Link      string
	Status    uint8
	Etag      string
	UpdatedAt time.Time
	ID        string
	Etag_2    string
}

func (q *Queries) UpdateAppWithEtag(ctx context.Context, arg UpdateAppWithEtagParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateAppWithEtag,
		arg.Name,
		arg.Link,
		arg.Status,
		arg.Etag,
		arg.UpdatedAt,
		arg.ID,
		arg.Etag_2,
	)
}
